name: boke
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  responsive_builder: ^0.2.0+2
  get_it: ^4.0.2
  provider_architecture: ^1.1.1+1
  url_launcher: ^5.4.10
  dartz: ^0.9.1
  equatable: ^1.2.0
  markdown_widget: ^1.2.3
  loveli_core:
    path: plugins/loveli_core

  ## 组件库
  getflutter: ^1.0.11
  flutter_tagging: ^2.2.0+3


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - assets/images/
